# Generated by Django 5.1.1 on 2025-08-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='can_manage_rates',
            field=models.BooleanField(default=False, help_text='Can manage shipping rates'),
        ),
    ]
