# Generated by Django 5.1.1 on 2025-09-14 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customeruser_can_manage_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Phone number verified via SMS'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='region',
            field=models.CharField(choices=[('US-AL', 'Alabama'), ('US-AK', 'Alaska'), ('US-AZ', 'Arizona'), ('US-AR', 'Arkansas'), ('US-CA', 'California'), ('US-CO', 'Colorado'), ('US-CT', 'Connecticut'), ('US-DE', 'Delaware'), ('US-FL', 'Florida'), ('US-GA', 'Georgia'), ('US-HI', 'Hawaii'), ('US-ID', 'Idaho'), ('US-IL', 'Illinois'), ('US-IN', 'Indiana'), ('US-IA', 'Iowa'), ('US-KS', 'Kansas'), ('US-KY', 'Kentucky'), ('US-LA', 'Louisiana'), ('US-ME', 'Maine'), ('US-MD', 'Maryland'), ('US-MA', 'Massachusetts'), ('US-MI', 'Michigan'), ('US-MN', 'Minnesota'), ('US-MS', 'Mississippi'), ('US-MO', 'Missouri'), ('US-MT', 'Montana'), ('US-NE', 'Nebraska'), ('US-NV', 'Nevada'), ('US-NH', 'New Hampshire'), ('US-NJ', 'New Jersey'), ('US-NM', 'New Mexico'), ('US-NY', 'New York'), ('US-NC', 'North Carolina'), ('US-ND', 'North Dakota'), ('US-OH', 'Ohio'), ('US-OK', 'Oklahoma'), ('US-OR', 'Oregon'), ('US-PA', 'Pennsylvania'), ('US-RI', 'Rhode Island'), ('US-SC', 'South Carolina'), ('US-SD', 'South Dakota'), ('US-TN', 'Tennessee'), ('US-TX', 'Texas'), ('US-UT', 'Utah'), ('US-VT', 'Vermont'), ('US-VA', 'Virginia'), ('US-WA', 'Washington'), ('US-WV', 'West Virginia'), ('US-WI', 'Wisconsin'), ('US-WY', 'Wyoming'), ('INTL-CANADA', 'Canada'), ('INTL-MEXICO', 'Mexico'), ('INTL-UK', 'United Kingdom'), ('INTL-GERMANY', 'Germany'), ('INTL-FRANCE', 'France'), ('INTL-CHINA', 'China'), ('INTL-JAPAN', 'Japan'), ('INTL-SOUTH-KOREA', 'South Korea'), ('INTL-AUSTRALIA', 'Australia'), ('INTL-BRAZIL', 'Brazil'), ('INTL-INDIA', 'India'), ('INTL-OTHER', 'Other International')], max_length=20),
        ),
        migrations.CreateModel(
            name='ResetPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset PIN',
                'verbose_name_plural': 'Password Reset PINs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification PIN',
                'verbose_name_plural': 'Verification PINs',
                'ordering': ['-created_at'],
            },
        ),
    ]
