# Generated by Django 5.1.1 on 2025-09-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customeruser_is_verified_alter_customeruser_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='nickname',
            field=models.CharField(blank=True, help_text='Optional nickname or display name', max_length=50),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company or business name', max_length=100),
        ),
    ]
