# Generated by Django 5.1.1 on 2025-09-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customeruser_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='accessible_warehouses',
            field=models.JSONField(default=list, help_text="List of warehouses this user can access (e.g., ['accra', 'kumasi', 'tema'])"),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='region',
            field=models.CharField(choices=[('GREATER_ACCRA', 'Greater Accra'), ('ASHANTI', 'Ashanti'), ('WESTERN', 'Western'), ('CENTRAL', 'Central'), ('VOLTA', 'Volta'), ('EASTERN', 'Eastern'), ('NORTHERN', 'Northern'), ('UPPER_EAST', 'Upper East'), ('UPPER_WEST', 'Upper West'), ('BRONG_AHAFO', 'Brong Ahafo'), ('WESTERN_NORTH', 'Western North'), ('AHAFO', 'Ahafo'), ('BONO', 'Bono'), ('BONO_EAST', 'Bono East'), ('OTI', 'Oti'), ('NORTH_EAST', 'North East'), ('SAVANNAH', 'Savannah')], max_length=20),
        ),
    ]
