# Generated by Django 5.1.1 on 2025-10-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customeruser_accessible_warehouses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='shipping_mark',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
