# Generated by Django 5.1.1 on 2025-10-05 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customeruser_shipping_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBulkUploadTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='QUEUED', max_length=16)),
                ('total_customers', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_upload_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Bulk Upload Task',
                'verbose_name_plural': 'Customer Bulk Upload Tasks',
                'indexes': [models.Index(fields=['task_id'], name='users_custo_task_id_c19c37_idx'), models.Index(fields=['status'], name='users_custo_status_af0750_idx')],
            },
        ),
    ]
