# Generated by Django 5.2.3 on 2025-10-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customerbulkuploadtask'),
        ('users', '0010_populate_roles_from_user_role'),
    ]

    operations = [
    ]
