# Generated by Django 5.2.3 on 2025-10-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_merge_20251017_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='roles',
            field=models.JSONField(blank=True, default=list, help_text="List of roles assigned to this user (e.g., ['CUSTOMER','ADMIN'])"),
        ),
    ]
