# Generated by Django 5.1.1 on 2025-08-18 18:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(help_text='Tracking ID or Tracking Number for the shipment', max_length=100)),
                ('item_name', models.CharField(help_text='Name of the item being claimed', max_length=200)),
                ('item_description', models.TextField(help_text='Detailed description of the item and the issue')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESOLVED', 'Resolved')], default='PENDING', help_text='Current status of the claim', max_length=20)),
                ('shipping_mark', models.CharField(help_text="Customer's shipping mark (copied from customer record)", max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the claim was submitted')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the claim was last updated')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from admin review', null=True)),
                ('customer', models.ForeignKey(help_text='Customer who submitted this claim', on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Claim',
                'verbose_name_plural': 'Claims',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shipping_mark'], name='claims_clai_shippin_61667e_idx'), models.Index(fields=['tracking_id'], name='claims_clai_trackin_d93d82_idx'), models.Index(fields=['status'], name='claims_clai_status_b4f911_idx'), models.Index(fields=['created_at'], name='claims_clai_created_d933ce_idx')],
            },
        ),
    ]
