# Generated by Django 5.1.1 on 2025-09-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='image_1',
            field=models.ImageField(blank=True, help_text='First supporting image for the claim', null=True, upload_to='claims/images/'),
        ),
        migrations.AddField(
            model_name='claim',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Second supporting image for the claim', null=True, upload_to='claims/images/'),
        ),
        migrations.AddField(
            model_name='claim',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Third supporting image for the claim', null=True, upload_to='claims/images/'),
        ),
    ]
