# Generated by Django 5.2.3 on 2025-10-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief title for the daily update', max_length=200)),
                ('content', models.TextField(help_text='Detailed content of the update')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Priority level of the update', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this update should expire (optional)', null=True)),
            ],
            options={
                'verbose_name': 'Daily Update',
                'verbose_name_plural': 'Daily Updates',
                'ordering': ['-created_at'],
            },
        ),
    ]
