# Generated by Django 5.1.1 on 2025-10-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_updates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyupdate',
            name='attachment',
            field=models.FileField(blank=True, help_text='Attach a document file (PDF, Excel, Word, etc.)', null=True, upload_to='daily_updates/attachments/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='dailyupdate',
            name='attachment_name',
            field=models.CharField(blank=True, help_text='Display name for the attachment', max_length=255),
        ),
        migrations.AddField(
            model_name='dailyupdate',
            name='attachment_size',
            field=models.IntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
    ]
