# Generated by Django 5.2.3 on 2025-10-01 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_updates', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dailyupdate',
            new_name='daily_updat_priorit_55f7fa_idx',
            old_name='daily_updat_priorit_a7b4e3_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyupdate',
            new_name='daily_updat_expires_b263e2_idx',
            old_name='daily_updat_expires_e8b4d7_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyupdate',
            new_name='daily_updat_created_a24626_idx',
            old_name='daily_updat_created_f9c5a8_idx',
        ),
    ]
