# Generated by Django 5.1.1 on 2025-10-08 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_updates', '0002_dailyupdate_attachment_dailyupdate_attachment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyupdate',
            name='content',
            field=models.TextField(help_text='Detailed content of the update (max 20,000 characters)', validators=[django.core.validators.MaxLengthValidator(20000)]),
        ),
    ]
