# Generated by Django 5.1.1 on 2025-06-27 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodsRecieved', '0004_goodsreceivedchina_method_of_shipping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivedchina',
            name='customer',
            field=models.ForeignKey(default=None, help_text='Customer who owns this shipment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='china_goods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceivedghana',
            name='customer',
            field=models.ForeignKey(default=None, help_text='Customer who owns this shipment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ghana_goods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceivedghana',
            name='method_of_shipping',
            field=models.CharField(choices=[('AIR', 'Air'), ('SEA', 'Sea')], default='SEA', help_text='Method of shipping for the goods', max_length=20),
        ),
        migrations.AlterField(
            model_name='goodsreceivedchina',
            name='shipping_mark',
            field=models.CharField(help_text="Customer's shipping mark identifier", max_length=20),
        ),
        migrations.AlterField(
            model_name='goodsreceivedghana',
            name='shipping_mark',
            field=models.CharField(help_text="Customer's shipping mark identifier", max_length=20),
        ),
        migrations.AlterField(
            model_name='goodsreceivedghana',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('READY_FOR_DELIVERY', 'Ready for Delivery'), ('FLAGGED', 'Flagged'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='goodsreceivedchina',
            index=models.Index(fields=['customer', 'status'], name='GoodsReciev_custome_6364f3_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceivedchina',
            index=models.Index(fields=['customer', 'date_received'], name='GoodsReciev_custome_6a586c_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceivedghana',
            index=models.Index(fields=['customer', 'status'], name='GoodsReciev_custome_c0bdb0_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceivedghana',
            index=models.Index(fields=['customer', 'date_received'], name='GoodsReciev_custome_ea0ca3_idx'),
        ),
    ]
