# Generated by Django 5.1.1 on 2025-09-14 17:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GoodsRecieved', '0006_remove_goodsreceivedchina_goodsreciev_custome_6364f3_idx_and_more'),
        ('cargo', '0003_alter_clientshipmentsummary_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('shipping_mark', models.CharField(max_length=50)),
                ('supply_tracking', models.CharField(max_length=100, unique=True)),
                ('cbm', models.DecimalField(decimal_places=3, help_text='Cubic meters (CBM)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantity', models.PositiveIntegerField(help_text='Number of items/pieces', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('demurrage', 'Demurrage')], db_index=True, default='pending', max_length=20)),
                ('method_of_shipping', models.CharField(choices=[('air', 'Air'), ('sea', 'Sea')], default='sea', help_text='Method of shipping', max_length=20)),
                ('date_received', models.DateTimeField(help_text='When goods were received in China warehouse')),
                ('date_shipped', models.DateTimeField(blank=True, help_text='When goods left China', null=True)),
                ('date_delivered', models.DateTimeField(blank=True, help_text='When goods were received in Ghana', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargo_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment', to='cargo.cargoitem')),
                ('goods_received_china', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_china', to='GoodsRecieved.goodsreceivedchina')),
                ('goods_received_ghana', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_ghana', to='GoodsRecieved.goodsreceivedghana')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'ordering': ['-date_received'],
                'indexes': [models.Index(fields=['status'], name='Shipments_s_status_9dcfd5_idx'), models.Index(fields=['shipping_mark'], name='Shipments_s_shippin_2b45d5_idx'), models.Index(fields=['supply_tracking'], name='Shipments_s_supply__345325_idx')],
            },
        ),
    ]
