# Generated by Django 5.1.1 on 2025-09-16 20:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipments',
            name='cbm',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Cubic meters (CBM)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
    ]
