# Generated by Django 5.1.1 on 2025-06-26 11:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceivedChina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('shipping_mark', models.CharField(help_text="Customer's shipping mark identifier", max_length=20, unique=True)),
                ('supply_tracking', models.CharField(help_text="Supplier's tracking number", max_length=50, unique=True)),
                ('cbm', models.DecimalField(decimal_places=3, help_text='Cubic meters (CBM)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantity', models.PositiveIntegerField(help_text='Number of items/pieces', validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True, help_text='Detailed description of the goods', null=True)),
                ('location', models.CharField(choices=[('GUANGZHOU', 'Guangzhou'), ('SHENZHEN', 'Shenzhen'), ('SHANGHAI', 'Shanghai'), ('YIWU', 'Yiwu'), ('OTHER', 'Other')], default='GUANGZHOU, China', help_text='Warehouse location in China', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('READY_FOR_SHIPPING', 'Ready for Shipping'), ('FLAGGED', 'Flagged'), ('SHIPPED', 'Shipped'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('date_received', models.DateTimeField(auto_now_add=True, help_text='When goods were received in warehouse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_name', models.CharField(blank=True, help_text='Name of the supplier', max_length=100, null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated value in USD', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notes', models.TextField(blank=True, help_text='Internal notes for staff', null=True)),
            ],
            options={
                'verbose_name': 'Goods Received (China)',
                'verbose_name_plural': 'Goods Received (China)',
                'ordering': ['-date_received'],
                'indexes': [models.Index(fields=['status', 'date_received'], name='GoodsReciev_status_25d8c1_idx'), models.Index(fields=['shipping_mark'], name='GoodsReciev_shippin_ac7c91_idx'), models.Index(fields=['supply_tracking'], name='GoodsReciev_supply__8b43fd_idx')],
            },
        ),
    ]
