# Generated by Django 5.1.1 on 2025-08-17 17:27

import django.core.validators
import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('NORMAL_GOODS', 'Normal Goods'), ('SPECIAL_GOODS', 'Special Goods'), ('SMALL_GOODS', 'Small Goods')], max_length=20)),
                ('rate_type', models.CharField(choices=[('SEA_RATES', 'Sea Rates'), ('AIR_RATES', 'Air Rates')], max_length=15)),
                ('title', models.CharField(max_length=100, verbose_name='Rate title')),
                ('description', models.TextField(blank=True)),
                ('origin_country', models.CharField(max_length=100)),
                ('destination_country', models.CharField(max_length=100)),
                ('office_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rate amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rate',
                'verbose_name_plural': 'Rates',
                'ordering': ['category', 'rate_type', 'origin_country', 'destination_country', 'title'],
                'indexes': [models.Index(fields=['category', 'rate_type'], name='rates_rate_categor_95eb31_idx'), models.Index(fields=['origin_country', 'destination_country'], name='rates_rate_origin__4c70f6_idx')],
                'constraints': [models.UniqueConstraint(fields=('category', 'rate_type', 'origin_country', 'destination_country', 'office_name', 'title'), name='uniq_rate_by_route_office_title'), models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('category', 'rate_type', 'origin_country', 'destination_country', 'office_name', 'amount'), name='uniq_rate_by_route_office_amount')],
            },
        ),
    ]
