# Generated by Django 5.1.1 on 2025-09-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rate',
            name='uniq_rate_by_route_office_amount',
        ),
        migrations.AddConstraint(
            model_name='rate',
            constraint=models.UniqueConstraint(fields=('category', 'rate_type', 'origin_country', 'destination_country', 'office_name', 'amount'), name='uniq_rate_by_route_office_amount'),
        ),
    ]
