# Generated by Django 5.1.1 on 2025-09-16 13:59

import settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admingeneralsettings',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Admin profile picture', null=True, upload_to='admin_profiles/', validators=[settings.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='companyoffice',
            name='office_image',
            field=models.ImageField(blank=True, help_text='Office image (drag & drop)', null=True, upload_to='office_images/', validators=[settings.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='invoicemetasettings',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='Company logo for invoices (drag & drop)', null=True, upload_to='invoice_assets/', validators=[settings.models.validate_image_file]),
        ),
    ]
