# Generated by Django 5.1.1 on 2025-09-17 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_admingeneralsettings_profile_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_broadcast', models.BooleanField(default=False, help_text='Send to all clients')),
                ('target_shipping_marks', models.JSONField(blank=True, default=list, help_text='List of shipping marks to target (if not broadcast)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.IntegerField(default=0)),
                ('read_count', models.IntegerField(default=0)),
                ('sender', models.ForeignKey(limit_choices_to={'user_role__in': ['ADMIN', 'SUPER_ADMIN']}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('target_clients', models.ManyToManyField(blank=True, limit_choices_to={'user_role': 'CUSTOMER'}, related_name='received_admin_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Message',
                'verbose_name_plural': 'Admin Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('notification_type', models.CharField(choices=[('admin_message', 'Admin Message'), ('system_alert', 'System Alert'), ('shipment_update', 'Shipment Update'), ('warehouse_notification', 'Warehouse Notification')], default='system_alert', max_length=25)),
                ('warehouse', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('action_required', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_notifications', to='settings.adminmessage')),
                ('recipient', models.ForeignKey(limit_choices_to={'user_role': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Notification',
                'verbose_name_plural': 'Client Notifications',
                'ordering': ['-created_at'],
                'unique_together': {('admin_message', 'recipient')},
            },
        ),
    ]
