# Generated by Django 5.1.1 on 2025-09-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_adminmessage_clientnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DollarRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_value', models.DecimalField(decimal_places=2, help_text='Exchange rate value (GHS per USD)', max_digits=10)),
                ('description', models.CharField(blank=True, help_text='Optional description for this rate', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rate is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dollar Exchange Rate',
                'verbose_name_plural': 'Dollar Exchange Rates',
                'ordering': ['-created_at'],
            },
        ),
    ]
