# Generated by Django 5.2.3 on 2025-10-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_update_shipping_mark_formats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DollarRate',
        ),
        migrations.AlterField(
            model_name='shippingmarkformatsettings',
            name='default_format_template',
            field=models.CharField(default='PM {name}', help_text='Default format when no rules match', max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingmarkformattingrule',
            name='format_template',
            field=models.CharField(default='PM{prefix} {name}', help_text='Format template: {prefix}, {name}, {counter}', max_length=100),
        ),
    ]
