# Generated by Django 5.2.3 on 2025-10-06 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_delete_dollarrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmarkformatsettings',
            name='max_shipping_mark_length',
            field=models.IntegerField(default=20, help_text='Maximum shipping mark length (default: 20)', validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='shippingmarkformatsettings',
            name='min_shipping_mark_length',
            field=models.IntegerField(default=10, help_text='Minimum shipping mark length (default: 10)', validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
