# Generated by Django 5.1.1 on 2025-06-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodsRecieved', '0002_goodsreceivedghana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceivedchina',
            name='location',
            field=models.CharField(choices=[('GUANGZHOU', 'Guangzhou'), ('SHENZHEN', 'Shenzhen'), ('SHANGHAI', 'Shanghai'), ('YIWU', 'Yiwu'), ('OTHER', 'Other')], default='GUANGZHOU', help_text='Warehouse location in China', max_length=20),
        ),
        migrations.AlterField(
            model_name='goodsreceivedghana',
            name='location',
            field=models.CharField(choices=[('ACCRA', 'Accra'), ('KUMASI', 'Kumasi'), ('TAKORADI', 'Takoradi'), ('OTHER', 'Other')], default='ACCRA', help_text='Warehouse location in Ghana', max_length=20),
        ),
    ]
