# Generated by Django 5.1.1 on 2025-06-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodsRecieved', '0003_alter_goodsreceivedchina_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivedchina',
            name='method_of_shipping',
            field=models.CharField(choices=[('AIR', 'Air'), ('SEA', 'Sea')], default='SEA', help_text='Method of shipping for the goods', max_length=20),
        ),
    ]
