# Generated by Django 5.1.1 on 2025-09-14 17:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodsRecieved', '0005_goodsreceivedchina_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='goodsreceivedchina',
            name='GoodsReciev_custome_6364f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='goodsreceivedchina',
            name='GoodsReciev_custome_6a586c_idx',
        ),
        migrations.RemoveIndex(
            model_name='goodsreceivedghana',
            name='GoodsReciev_custome_c0bdb0_idx',
        ),
        migrations.RemoveIndex(
            model_name='goodsreceivedghana',
            name='GoodsReciev_custome_ea0ca3_idx',
        ),
        migrations.RemoveField(
            model_name='goodsreceivedchina',
            name='estimated_value',
        ),
        migrations.RemoveField(
            model_name='goodsreceivedchina',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='goodsreceivedchina',
            name='location',
        ),
        migrations.RemoveField(
            model_name='goodsreceivedchina',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='goodsreceivedchina',
            name='supplier_name',
        ),
        migrations.RemoveField(
            model_name='goodsreceivedghana',
            name='estimated_value',
        ),
        migrations.RemoveField(
            model_name='goodsreceivedghana',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='goodsreceivedghana',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='goodsreceivedghana',
            name='supplier_name',
        ),
        migrations.AlterField(
            model_name='goodsreceivedchina',
            name='cbm',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Cubic meters (CBM)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='goodsreceivedchina',
            name='customer',
            field=models.ForeignKey(default='', help_text='Customer who owns this shipment', on_delete=django.db.models.deletion.CASCADE, related_name='china_goods', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodsreceivedchina',
            name='date_received',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='goodsreceivedchina',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceivedchina',
            name='shipping_mark',
            field=models.CharField(db_index=True, help_text="Customer's shipping mark identifier (auto-synced from user)", max_length=20),
        ),
        migrations.AlterField(
            model_name='goodsreceivedghana',
            name='cbm',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='goodsreceivedghana',
            name='customer',
            field=models.ForeignKey(default='', help_text='Customer who owns this shipment', on_delete=django.db.models.deletion.CASCADE, related_name='ghana_goods', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodsreceivedghana',
            name='date_received',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='goodsreceivedghana',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceivedghana',
            name='location',
            field=models.CharField(choices=[('ACCRA', 'Accra'), ('KUMASI', 'Kumasi'), ('TAKORADI', 'Takoradi'), ('OTHER', 'Other')], default='ACCRA', max_length=20),
        ),
        migrations.AlterField(
            model_name='goodsreceivedghana',
            name='method_of_shipping',
            field=models.CharField(choices=[('AIR', 'Air'), ('SEA', 'Sea')], default='SEA', max_length=20),
        ),
        migrations.AlterField(
            model_name='goodsreceivedghana',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='goodsreceivedghana',
            name='shipping_mark',
            field=models.CharField(db_index=True, help_text="Customer's shipping mark identifier (auto-synced from user)", max_length=20),
        ),
        migrations.AlterField(
            model_name='goodsreceivedghana',
            name='supply_tracking',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='goodsreceivedghana',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddIndex(
            model_name='goodsreceivedchina',
            index=models.Index(fields=['shipping_mark', 'status'], name='GoodsReciev_shippin_7152f2_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceivedghana',
            index=models.Index(fields=['shipping_mark', 'status'], name='GoodsReciev_shippin_907d7d_idx'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceivedchina',
            constraint=models.UniqueConstraint(fields=('customer', 'supply_tracking'), name='unique_customer_supply_tracking_china'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceivedghana',
            constraint=models.UniqueConstraint(fields=('customer', 'supply_tracking'), name='unique_customer_supply_tracking_ghana'),
        ),
    ]
