# Generated by Django 5.1.1 on 2025-09-16 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodsRecieved', '0006_remove_goodsreceivedchina_goodsreciev_custome_6364f3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceivedchina',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer who owns this shipment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='china_goods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='goodsreceivedghana',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer who owns this shipment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ghana_goods', to=settings.AUTH_USER_MODEL),
        ),
    ]
