# Generated by Django 5.1.1 on 2025-09-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodsRecieved', '0007_alter_goodsreceivedchina_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceivedchina',
            name='shipping_mark',
            field=models.CharField(blank=True, db_index=True, help_text="Customer's shipping mark identifier (auto-synced from user)", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceivedghana',
            name='shipping_mark',
            field=models.CharField(blank=True, db_index=True, help_text="Customer's shipping mark identifier (auto-synced from user)", max_length=20, null=True),
        ),
    ]
