# Generated by Django 5.1.1 on 2025-09-16 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoodsRecieved', '0008_alter_goodsreceivedchina_shipping_mark_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='goodsreceivedchina',
            name='unique_customer_supply_tracking_china',
        ),
        migrations.RemoveConstraint(
            model_name='goodsreceivedghana',
            name='unique_customer_supply_tracking_ghana',
        ),
    ]
