# Generated by Django 5.1.1 on 2025-09-16 19:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodsRecieved', '0009_remove_goodsreceivedchina_unique_customer_supply_tracking_china_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceivedghana',
            name='cbm',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Cubic meters - optional for air cargo', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
    ]
