# Generated by Django 5.1.1 on 2025-09-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodsRecieved', '0010_alter_goodsreceivedghana_cbm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceivedghana',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('READY_FOR_DELIVERY', 'Ready for Delivery'), ('FLAGGED', 'Flagged'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='READY_FOR_DELIVERY', max_length=20),
        ),
    ]
