# Generated by Django 5.1.1 on 2025-09-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodsRecieved', '0011_change_ghana_status_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivedchina',
            name='date_loading',
            field=models.DateField(blank=True, help_text='Date when goods were loaded/processed', null=True),
        ),
        migrations.AddField(
            model_name='goodsreceivedghana',
            name='date_loading',
            field=models.DateField(blank=True, help_text='Date when goods were loaded/processed', null=True),
        ),
    ]
