# Generated by Django 5.1.1 on 2025-09-27 13:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodsRecieved', '0012_add_date_loading_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivedghana',
            name='breadth',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Breadth/Width in centimeters (for sea cargo CBM calculation)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='goodsreceivedghana',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters (for sea cargo CBM calculation)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='goodsreceivedghana',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length in centimeters (for sea cargo CBM calculation)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceivedghana',
            name='cbm',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Cubic meters - auto-calculated for sea cargo, manual for air cargo', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
    ]
