# Generated by Django 5.1.1 on 2025-09-28 00:32

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodsRecieved', '0013_add_dimensions_to_ghana_goods'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceivedContainer',
            fields=[
                ('container_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('container_type', models.CharField(choices=[('air', 'Air Goods'), ('sea', 'Sea Goods')], max_length=10)),
                ('location', models.CharField(choices=[('china', 'China Warehouse'), ('ghana', 'Ghana Warehouse')], max_length=20)),
                ('arrival_date', models.DateField()),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('total_weight', models.FloatField(blank=True, help_text='Total weight calculated from items', null=True)),
                ('total_cbm', models.FloatField(blank=True, help_text='Total CBM calculated from items', null=True)),
                ('total_items_count', models.IntegerField(default=0, help_text='Total number of items in container')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready_for_delivery', 'Ready for Delivery'), ('delivered', 'Delivered'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceivedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shipping_mark', models.CharField(db_index=True, help_text="Customer's shipping mark identifier", max_length=20)),
                ('supply_tracking', models.CharField(help_text="Supplier's tracking number", max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(help_text='Number of items/pieces')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cbm', models.DecimalField(blank=True, decimal_places=3, help_text='Cubic meters (CBM)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('length', models.FloatField(blank=True, help_text='Length in centimeters', null=True)),
                ('breadth', models.FloatField(blank=True, help_text='Breadth/Width in centimeters', null=True)),
                ('height', models.FloatField(blank=True, help_text='Height in centimeters', null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, help_text='Storage location within warehouse', max_length=50, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('READY_FOR_DELIVERY', 'Ready for Delivery'), ('FLAGGED', 'Flagged'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=25)),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_items', to='GoodsRecieved.goodsreceivedcontainer')),
                ('customer', models.ForeignKey(blank=True, help_text='Customer who owns this item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_received_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shipping_mark'], name='GoodsReciev_shippin_2176a3_idx'), models.Index(fields=['supply_tracking'], name='GoodsReciev_supply__b5bca8_idx'), models.Index(fields=['container', 'shipping_mark'], name='GoodsReciev_contain_268424_idx')],
            },
        ),
    ]
