# Generated by Django 5.1.1 on 2025-09-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodsRecieved', '0014_goodsreceivedcontainer_goodsreceiveditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivedcontainer',
            name='dollar_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dollar rate amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='goodsreceivedcontainer',
            name='selected_rate_id',
            field=models.CharField(blank=True, help_text='Selected rate ID from rates system', max_length=50, null=True),
        ),
    ]
