# Generated by Django 5.1.1 on 2025-09-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodsRecieved', '0015_goodsreceivedcontainer_dollar_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivedcontainer',
            name='rates',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='CBM/Weight rate amount', max_digits=10, null=True),
        ),
    ]
