# Generated by Django 5.1.1 on 2025-10-02 18:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodsRecieved', '0016_goodsreceivedcontainer_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceivedchina',
            name='cbm',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Cubic meters (CBM)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00001'))]),
        ),
        migrations.AlterField(
            model_name='goodsreceivedchina',
            name='shipping_mark',
            field=models.CharField(blank=True, db_index=True, help_text="Customer's shipping mark identifier (auto-synced from user)", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceivedghana',
            name='cbm',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Cubic meters - auto-calculated for sea cargo, manual for air cargo', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00001'))]),
        ),
    ]
