# Generated by Django 5.1.1 on 2025-10-04 07:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodsRecieved', '0017_alter_goodsreceivedchina_cbm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceiveditem',
            name='cbm',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Cubic meters (CBM)', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
    ]
