# Generated by Django 5.1.1 on 2025-06-26 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeruser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RenameField(
            model_name='customeruser',
            old_name='nickname',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='customeruser',
            name='accessible_warehouses',
            field=models.JSONField(default=list, help_text="List of warehouses this user can access (e.g., ['china', 'ghana'])"),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='can_access_admin_panel',
            field=models.BooleanField(default=False, help_text='Can access custom admin panel'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='can_create_users',
            field=models.BooleanField(default=False, help_text='Can create new users'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='can_manage_admins',
            field=models.BooleanField(default=False, help_text='Can create and manage other admins'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='can_manage_inventory',
            field=models.BooleanField(default=False, help_text='Can manage warehouse inventory'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='can_view_analytics',
            field=models.BooleanField(default=False, help_text='Can view system analytics'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin who created this user', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='user_role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('STAFF', 'Staff'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('SUPER_ADMIN', 'Super Admin')], default='CUSTOMER', help_text="User's role in the system", max_length=20),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='user_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('BUSINESS', 'Business')], default='INDIVIDUAL', help_text='Individual or Business user', max_length=20),
        ),
        migrations.AddIndex(
            model_name='customeruser',
            index=models.Index(fields=['user_role'], name='users_custo_user_ro_9c8640_idx'),
        ),
        migrations.AddIndex(
            model_name='customeruser',
            index=models.Index(fields=['is_active'], name='users_custo_is_acti_95bf7b_idx'),
        ),
        migrations.AddIndex(
            model_name='customeruser',
            index=models.Index(fields=['phone'], name='users_custo_phone_35b616_idx'),
        ),
    ]
