# Generated by Django 5.1.1 on 2025-07-04 12:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoContainer',
            fields=[
                ('container_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('cargo_type', models.CharField(choices=[('sea', 'Sea Cargo'), ('air', 'Air Cargo')], max_length=10)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('cbm', models.FloatField(blank=True, null=True)),
                ('load_date', models.DateField()),
                ('eta', models.DateField()),
                ('unloading_date', models.DateField(blank=True, null=True)),
                ('route', models.CharField(max_length=255)),
                ('rates', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stay_days', models.IntegerField(default=0)),
                ('delay_days', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('demurrage', 'Demurrage')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CargoItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('item_description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('cbm', models.FloatField()),
                ('unit_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('delayed', 'Delayed')], default='pending', max_length=20)),
                ('delivered_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_items', to=settings.AUTH_USER_MODEL)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_items', to='cargo.cargocontainer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientShipmentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_tracking', models.CharField(editable=False, max_length=100, unique=True)),
                ('total_cbm', models.FloatField(default=0)),
                ('total_quantity', models.IntegerField(default=0)),
                ('total_packages', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.cargocontainer')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('container', 'client')},
            },
        ),
    ]
