# Generated by Django 5.1.1 on 2025-09-14 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_alter_cargoitem_tracking_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientshipmentsummary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cargoitem',
            name='client_shipping_mark',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientshipmentsummary',
            name='client_shipping_mark',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientshipmentsummary',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('partially_delivered', 'Partially Delivered'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='cargocontainer',
            constraint=models.UniqueConstraint(fields=('container_id',), name='unique_container_id'),
        ),
        migrations.AddConstraint(
            model_name='cargoitem',
            constraint=models.UniqueConstraint(fields=('container', 'client_shipping_mark', 'tracking_id'), name='unique_container_client_tracking'),
        ),
        migrations.AddConstraint(
            model_name='clientshipmentsummary',
            constraint=models.UniqueConstraint(fields=('container', 'client_shipping_mark'), name='unique_container_client_summary'),
        ),
    ]
