# Generated by Django 5.1.1 on 2025-09-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0003_alter_clientshipmentsummary_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargoitem',
            name='cbm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
