# Generated by Django 5.1.1 on 2025-09-16 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0004_alter_cargoitem_cbm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cargoitem',
            name='unique_container_client_tracking',
        ),
        migrations.RemoveField(
            model_name='cargoitem',
            name='client_shipping_mark',
        ),
        migrations.AddConstraint(
            model_name='cargoitem',
            constraint=models.UniqueConstraint(fields=('container', 'client', 'tracking_id'), name='unique_container_client_tracking'),
        ),
    ]
