# Generated by Django 5.1.1 on 2025-09-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0006_update_air_container_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargocontainer',
            name='location',
            field=models.CharField(choices=[('china', 'China'), ('ghana', 'Ghana'), ('transit', 'In Transit')], default='china', max_length=20),
        ),
        migrations.AddField(
            model_name='cargocontainer',
            name='warehouse_type',
            field=models.CharField(choices=[('cargo', 'Cargo Operations'), ('goods_received', 'Goods Received')], default='cargo', max_length=20),
        ),
    ]
