# Generated by Django 5.1.1 on 2025-09-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0007_cargocontainer_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargocontainer',
            name='dollar_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
