# Generated by Django 5.1.1 on 2025-09-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0008_add_dollar_rate_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargoitem',
            name='item_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
