# Generated by Django 5.1.1 on 2025-09-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0009_make_item_description_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoitem',
            name='breadth',
            field=models.FloatField(blank=True, help_text='Breadth/Width in centimeters', null=True),
        ),
        migrations.AddField(
            model_name='cargoitem',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in centimeters', null=True),
        ),
        migrations.AddField(
            model_name='cargoitem',
            name='length',
            field=models.FloatField(blank=True, help_text='Length in centimeters', null=True),
        ),
    ]
