# Generated by Django 5.1.1 on 2025-10-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0010_add_dimensions_to_cargo_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientshipmentsummary',
            name='client_shipping_mark',
            field=models.CharField(max_length=100),
        ),
    ]
