# Generated by Django 5.2.3 on 2025-10-08 15:02

from django.conf import settings
from django.db import migrations, models


def remove_duplicate_container_clients(apps, schema_editor):
    """
    Remove duplicate CargoItem entries with the same container and client.
    Keep the most recent one (latest created_at).
    """
    CargoItem = apps.get_model('cargo', 'CargoItem')
    
    # Use raw SQL to avoid trigger issues with ORM deletes
    # First, identify duplicates and keep only the most recent one
    with schema_editor.connection.cursor() as cursor:
        # Delete duplicates, keeping only the row with the latest created_at for each (container, client) pair
        cursor.execute("""
            DELETE FROM cargo_cargoitem
            WHERE id IN (
                SELECT id
                FROM (
                    SELECT id,
                           ROW_NUMBER() OVER (
                               PARTITION BY container_id, client_id 
                               ORDER BY created_at DESC
                           ) as row_num
                    FROM cargo_cargoitem
                ) t
                WHERE row_num > 1
            );
        """)
        deleted_count = cursor.rowcount
        
        if deleted_count > 0:
            print(f"Removed {deleted_count} duplicate CargoItem entries")


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0011_alter_clientshipmentsummary_client_shipping_mark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # First, remove duplicates using raw SQL to avoid trigger events
        migrations.RunPython(
            remove_duplicate_container_clients, 
            migrations.RunPython.noop
        ),
        # Then proceed with constraint changes
        migrations.RemoveConstraint(
            model_name='cargoitem',
            name='unique_container_client_tracking',
        ),
        migrations.AlterField(
            model_name='cargoitem',
            name='tracking_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='cargoitem',
            constraint=models.UniqueConstraint(fields=('container', 'client'), name='unique_container_client'),
        ),
    ]
