# Generated by Django 5.2.3 on 2025-10-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0011_alter_clientshipmentsummary_client_shipping_mark'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cargoitem',
            name='unique_container_client_tracking',
        ),
        migrations.AlterField(
            model_name='cargoitem',
            name='tracking_id',
            field=models.CharField(max_length=100),
        ),
    ]
