# Generated by manual fix on 2025-10-09

from django.db import migrations


def skip_duplicate_removal(apps, schema_editor):
    """
    This migration previously removed duplicate CargoItem entries.
    However, duplicates are intentionally allowed and preserved now.
    This function does nothing but logs a message to confirm the skip.
    """
    print("⚠️ Skipping duplicate removal — preserving all CargoItem entries.")


class Migration(migrations.Migration):
    """
    Safe migration that intentionally skips duplicate cleanup.
    Keeps data intact while preserving migration order.
    """

    dependencies = [
        ('cargo', '0012_remove_cargoitem_unique_container_client_tracking_and_more'),
    ]

    operations = [
        migrations.RunPython(
            skip_duplicate_removal,
            migrations.RunPython.noop
        ),
    ]
