# Generated by Django 5.1.1 on 2025-10-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Apply the schema changes that were originally in 0012.
    This is separated to avoid "pending trigger events" error in PostgreSQL.
    """

    dependencies = [
        ('cargo', '0012_remove_cargoitem_unique_container_client_tracking_and_more'),
    ]

    operations = [
        # Schema changes from original migration 0012
        migrations.RemoveConstraint(
            model_name='cargoitem',
            name='unique_container_client_tracking',
        ),
        migrations.AlterField(
            model_name='cargoitem',
            name='tracking_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='cargoitem',
            constraint=models.UniqueConstraint(fields=('container', 'client'), name='unique_container_client'),
        ),
    ]
