# Generated by Django 5.1.1 on 2025-10-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0013_remove_duplicate_container_clients'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cargoitem',
            constraint=models.UniqueConstraint(fields=('container', 'client'), name='unique_container_client'),
        ),
    ]
