# Generated by manual fix on 2025-10-09

from django.db import migrations


def fix_unique_constraint(apps, schema_editor):
    """
    Fix the unique constraint issue by checking what exists and applying only what's needed.
    This migration handles cases where previous deployments partially succeeded.
    """
    with schema_editor.connection.cursor() as cursor:
        # Check if the old constraint exists
        cursor.execute("""
            SELECT constraint_name 
            FROM information_schema.table_constraints 
            WHERE table_name = 'cargo_cargoitem' 
            AND constraint_name = 'unique_container_client_tracking'
        """)
        has_old_constraint = cursor.fetchone()
        
        # Check if the new constraint already exists
        cursor.execute("""
            SELECT constraint_name 
            FROM information_schema.table_constraints 
            WHERE table_name = 'cargo_cargoitem' 
            AND constraint_name = 'unique_container_client'
        """)
        has_new_constraint = cursor.fetchone()
        
        # Remove old constraint if it exists
        if has_old_constraint:
            cursor.execute("""
                ALTER TABLE cargo_cargoitem 
                DROP CONSTRAINT unique_container_client_tracking
            """)
            print("✓ Removed old constraint: unique_container_client_tracking")
        else:
            print("✓ Old constraint already removed")
        
        # Add new constraint only if it doesn't exist
        if not has_new_constraint:
            cursor.execute("""
                ALTER TABLE cargo_cargoitem 
                ADD CONSTRAINT unique_container_client 
                UNIQUE (container_id, client_id)
            """)
            print("✓ Added new constraint: unique_container_client")
        else:
            print("✓ Constraint unique_container_client already exists")


class Migration(migrations.Migration):
    """
    Cleanup migration to handle constraint changes that may have partially applied.
    """

    dependencies = [
        ('cargo', '0013_remove_duplicate_container_clients'),
    ]

    operations = [
        migrations.RunPython(
            fix_unique_constraint,
            migrations.RunPython.noop
        ),
    ]
