# Generated by Django 5.1.1 on 2025-10-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0014_fix_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargoitem',
            name='tracking_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
